"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import AppShell from "@/components/AppShell";
import PageHeader from "@/components/PageHeader";

const tabs=["Pulpit","Zbiórki","Wiadomości","Użytkownicy"];
export default function AdminPage(){
 const [tab,setTab]=useState("Pulpit"),[notice,setNotice]=useState(""),[meetings,setMeetings]=useState([{title:"Zbiórka meczowa",date:"12 wrz · 08:15",place:"Lobby hotelowe",confirmed:9,total:12}]);
 function addMeeting(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);setMeetings(v=>[{title:String(d.get("title")),date:String(d.get("date")).replace("T"," · "),place:String(d.get("place")),confirmed:0,total:12},...v]);e.currentTarget.reset();setNotice("Zbiórka została utworzona i wysłana zawodnikom.")}
 return <AppShell><PageHeader eyebrow="CENTRUM DOWODZENIA" title="Panel administratora"/>
  <div className="adminIdentity"><span>ADMIN</span><div><strong>Mateusz Pitek</strong><small>Pełny dostęp do drużyny</small></div><i>● ONLINE</i></div>
  <div className="segmented adminTabs">{tabs.map(x=><button className={tab===x?"active":""} onClick={()=>{setTab(x);setNotice("")}} key={x}>{x}</button>)}</div>
  {tab==="Pulpit"&&<><section className="adminHero"><div><small>NAJBLIŻSZY MECZ · 12 WRZ, 09:30</small><h2>OIRP Wrocław <b>vs</b> Lawyers Madrid</h2><p>Boisko Centralne · zbiórka 08:15</p></div><strong>9/12<small>potwierdzonych</small></strong></section><section className="adminCommandGrid"><button onClick={()=>setTab("Zbiórki")}><i>01</i><span><strong>Zbiórki</strong><small>Utwórz i sprawdź obecność</small></span><b>→</b></button><button onClick={()=>setTab("Wiadomości")}><i>02</i><span><strong>Wiadomości</strong><small>Wyślij komunikat push</small></span><b>→</b></button><Link href="/captain/lineup"><i>03</i><span><strong>Skład</strong><small>Ustal 7 zawodników i ławkę</small></span><b>→</b></Link><Link href="/captain/tactics"><i>04</i><span><strong>Taktyka</strong><small>Ustaw stałe fragmenty</small></span><b>→</b></Link></section><div className="adminStatus"><span><b>12</b> zawodników</span><span><b>1</b> pilny komunikat</span><span><b>3</b> mecze w grupie</span></div></>}
  {tab==="Zbiórki"&&<><form className="formCard adminForm" onSubmit={addMeeting}><div className="fieldGrid"><label>NAZWA ZBIÓRKI<input name="title" placeholder="Zbiórka meczowa" required/></label><label>DATA I GODZINA<input name="date" type="datetime-local" required/></label></div><label>MIEJSCE<input name="place" placeholder="Lobby hotelowe" required/></label><label className="checkLabel"><input type="checkbox" defaultChecked/> Wyślij powiadomienie push do zawodników</label><button className="primary wide">Utwórz zbiórkę</button></form><section className="meetingList">{meetings.map(m=><article key={m.title+m.date}><div><small>{m.date}</small><h3>{m.title}</h3><p>{m.place}</p></div><strong>{m.confirmed}/{m.total}<small>potwierdzonych</small></strong></article>)}</section></>}
  {tab==="Wiadomości"&&<form className="formCard adminForm" onSubmit={e=>{e.preventDefault();setNotice("Komunikat został wysłany.")}}><div className="fieldGrid"><label>PRIORYTET<select><option>Pilny</option><option>Zwykły</option></select></label><label>ODBIORCY<select><option>Wszyscy zawodnicy</option><option>Sztab</option><option>Wszyscy</option></select></label></div><label>TYTUŁ<input defaultValue="Zbiórka przed meczem" required/></label><label>TREŚĆ<textarea defaultValue="Lobby hotelowe, godz. 08:15. Zabierz biały komplet." required/></label><label className="checkLabel"><input type="checkbox" defaultChecked/> Wyślij jako powiadomienie push</label><button className="primary wide">Wyślij komunikat</button></form>}
  {tab==="Użytkownicy"&&<section className="adminList userRoles">{[["M. Pitek","Administrator · Kapitan"],["T. Mazur","Sztab · Zawodnik"],["K. Nowak","Zawodnik"],["Anna K.","Kibic"]].map(x=><article key={x[0]}><span>{x[0].split(" ").map(y=>y[0]).join("")}</span><div><strong>{x[0]}</strong><small>{x[1]}</small></div><button>Zmień rolę</button></article>)}</section>}
  {notice&&<p className="adminNotice">{notice}</p>}
 </AppShell>
}
