"use client";
import { useState } from "react";
import PageHeader from "@/components/PageHeader";
type Point={x:number;y:number}; type Token=Point&{id:number;number:number;side:"ours"|"rival"}; type Route={from:Point;to:Point};
const phases=["Aut","Rzut wolny","Rzut rożny"];
const initial:Token[]=[{id:1,number:1,x:50,y:88,side:"ours"},{id:2,number:4,x:24,y:68,side:"ours"},{id:3,number:5,x:76,y:68,side:"ours"},{id:4,number:8,x:18,y:42,side:"ours"},{id:5,number:10,x:50,y:45,side:"ours"},{id:6,number:7,x:82,y:42,side:"ours"},{id:7,number:9,x:50,y:18,side:"ours"},{id:8,number:2,x:28,y:28,side:"rival"},{id:9,number:3,x:50,y:31,side:"rival"},{id:10,number:6,x:72,y:28,side:"rival"}];
export default function TacticsPage(){
 const [phase,setPhase]=useState("Aut"),[mode,setMode]=useState("Ofensywa"),[saved,setSaved]=useState(false); const [tokens,setTokens]=useState(initial),[ball,setBall]=useState<Point>({x:42,y:48}),[routes,setRoutes]=useState<Route[]>([]),[tool,setTool]=useState<"move"|"route">("move"),[routeStart,setRouteStart]=useState<Point|null>(null);
 function drag(event:React.PointerEvent<HTMLButtonElement>,id:number){if(tool!=="move")return;const pitch=event.currentTarget.parentElement?.getBoundingClientRect();if(!pitch)return;event.currentTarget.setPointerCapture(event.pointerId);const move=(e:PointerEvent)=>{const x=Math.min(94,Math.max(6,(e.clientX-pitch.left)/pitch.width*100));const y=Math.min(95,Math.max(5,(e.clientY-pitch.top)/pitch.height*100));setTokens(v=>v.map(t=>t.id===id?{...t,x,y}:t));setSaved(false)};const stop=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",stop)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",stop)}
 function boardTap(e:React.PointerEvent<HTMLElement>){if(tool!=="route"||e.target!==e.currentTarget)return;const r=e.currentTarget.getBoundingClientRect();const point={x:(e.clientX-r.left)/r.width*100,y:(e.clientY-r.top)/r.height*100};if(!routeStart)setRouteStart(point);else{setRoutes(v=>[...v,{from:routeStart,to:point}]);setRouteStart(null);setSaved(false)}}
 function moveBall(e:React.PointerEvent<HTMLButtonElement>){if(tool!=="move")return;const pitch=e.currentTarget.parentElement?.getBoundingClientRect();if(!pitch)return;const move=(p:PointerEvent)=>setBall({x:Math.min(96,Math.max(4,(p.clientX-pitch.left)/pitch.width*100)),y:Math.min(96,Math.max(4,(p.clientY-pitch.top)/pitch.height*100))});const stop=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",stop)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",stop)}
 return <main className="lineupShell"><PageHeader eyebrow="KAPITAN · TYLKO DRUŻYNA" title="Tablica taktyczna"/><div className="segmented">{phases.map(x=><button className={phase===x?"active":""} onClick={()=>{setPhase(x);setSaved(false)}} key={x}>{x}</button>)}</div><div className="tacticsToolbar"><div className="modeTabs"><button className={mode==="Ofensywa"?"active":""} onClick={()=>setMode("Ofensywa")}>Ofensywa</button><button className={mode==="Defensywa"?"active":""} onClick={()=>setMode("Defensywa")}>Defensywa</button></div><div className="boardTools"><button className={tool==="move"?"active":""} onClick={()=>setTool("move")}>Przesuwaj</button><button className={tool==="route"?"active":""} onClick={()=>setTool("route")}>Rysuj ruch</button></div></div><p className="boardHint">{tool==="move"?"Przeciągaj zawodników i piłkę po boisku.":routeStart?"Dotknij miejsca końcowego strzałki.":"Dotknij początku, a następnie końca ruchu."}</p>
 <section className={`pitch tacticsPitch tool-${tool}`} onPointerDown={boardTap}><div className="halfway"/><div className="centerCircle"/><div className="box top"/><div className="box bottom"/><svg className="routes" viewBox="0 0 100 100" preserveAspectRatio="none"><defs><marker id="arrow" markerWidth="5" markerHeight="5" refX="4" refY="2.5" orient="auto"><path d="M0,0 L5,2.5 L0,5 z"/></marker></defs>{routes.map((r,i)=><line key={i} x1={r.from.x} y1={r.from.y} x2={r.to.x} y2={r.to.y} markerEnd="url(#arrow)"/>)}</svg>{tokens.map(t=><button onPointerDown={e=>drag(e,t.id)} className={`tacticDot ${t.side}`} style={{left:`${t.x}%`,top:`${t.y}%`}} key={t.id}>{t.number}</button>)}<button aria-label="Piłka" className="tacticBall" style={{left:`${ball.x}%`,top:`${ball.y}%`}} onPointerDown={moveBall}>⚽</button></section>
 <div className="boardActions"><button onClick={()=>{setRoutes([]);setRouteStart(null)}}>Wyczyść strzałki</button><button onClick={()=>{setTokens(initial);setBall({x:42,y:48});setRoutes([])}}>Resetuj tablicę</button></div><section className="formCard compact"><label>NAZWA WARIANTU<input value={`${phase} A · ${mode}`} readOnly/></label><label>INSTRUKCJA<textarea defaultValue="Krótko do zawodnika nr 10, ruch napastnika za plecy obrońcy."/></label><button className="primary wide" onClick={()=>setSaved(true)}>{saved?"Taktyka zapisana ✓":"Zapisz taktykę"}</button></section></main>
}
